### PR TITLE
IE11 fix

### LINKED ISSUE #25: IE is not working. Probably chachedRect is not defined
https://github.com/RyoNkmr/stuck-js/blob/master/src/placeholder.js#L84

### PR DESCRIPTION
**Pull request by RyoNkmr**
fix(stuck-js): fix the bug that the placeholder element will be not found before placed on DOM in some c

fix #25

### CODE REVIEW

File: src/placeholder.ts [hunk 1]
```diff
@@ -44,9 +44,8 @@ export default class Placeholder {
 
     this.element = Placeholder.createPlaceholderElement()
     this.applyInitialStyles()
-    this.cachedRect = this.element && this.updateRect()
-
     Placeholder.wrap(this.original, this.element)
+    this.cachedRect = this.updateRect()
```
Comment (RyoNkmr) [inline src/placeholder.ts]: this is the point of this PR
